version: 0.17.7_b{build}
image: Visual Studio 2017
skip_tags: true

#rdp debug
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmd  

#branches:
#  only:
#  - master

environment:
  PRO_FILE: '%APPVEYOR_BUILD_FOLDER%\QuiteRSS.pro'

  matrix:
  - BUILD: Qt5.9-x64-msvc2017
    QTDIR: 'c:\qt\5.9\msvc2017_64'
    COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    QMAKESPEC: win32-msvc2013
    PRO_MAKE: nmake
    PRO_CHECK: nmake check

  - BUILD: Qt5.9-mingw32
    QTDIR: 'c:\qt\5.9\mingw491_32'
    COMPILERDIR: 'c:\qt\tools\mingw491_32\bin'
    QMAKESPEC: win32-g++
    PRO_MAKE: mingw32-make
    PRO_CHECK: mingw32-make check

  - BUILD: Qt5.9-x86-msvc2017
    QTDIR: 'c:\qt\5.9\msvc2015'
    COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    QMAKESPEC: win32-msvc2013
    PRO_MAKE: nmake
    PRO_CHECK: nmake check
    
   
install:
#- choco install curl 7zip # dependencywalker
- set QT_PLUGIN_PATH=%QTDIR%\plugins
- set "PATH=%QTDIR%\bin;%PATH%"
- if defined COMPILERDIR set "PATH=%COMPILERDIR%;%PATH%"
- '%COMPILERBAT%'

after_build:
- 7z a "%BUILD%.zip" ".\build\%BUILD%\release\target\*"
- dir "%APPVEYOR_BUILD_FOLDER%"
- dir "%APPVEYOR_BUILD_FOLDER%\build"

build_script:
- echo "building %BUILD%"
- mkdir build
- mkdir "build\%BUILD%"
- cd "build\%BUILD%"
- set
- qmake -r CONFIG+=release %QMAKE_OPTIONS% %PRO_FILE%
- '%PRO_MAKE%'
- cd ..\..

test_script:
- cd "build\%BUILD%"
- '%PRO_CHECK%'

artifacts:
- path: $(BUILD).zip

#deploy:
## FTP deployment provider settings
#- provider: FTP
#  protocol: ftps
#  host: prokudin.org
#  username: quitefuncy
#  password:
#    secure: GUuFDbSezZ7LmK+pzK1w930brvyL+MmmU4B+ItMsa+8=
#  folder: 'files\test'
